#---------------------------------------------------------------------------------------------------------------------#
#------------------------------------------- Site Settings ---------------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#

#---------------------------------------------------------------------------------------------------------------------#
#----------------------------------------- General Site Settings -------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#


title: Matthew Ryan Evans
description: Software Developer // Programer // Web Developer
email: matthewevans521@gmail.com

#---------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------- Navigation --------------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#

menu:
- {name: Home, url: '#header'}
- {name: About Me, url: '#about-me'}
- {name: Projects, url: '#projects'}
- {name: Contact, url: '#contact'}

#---------------------------------------------------------------------------------------------------------------------#
#------------------------------------------- About Me Section --------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#

blurb:  <strong>My name is Matthew Ryan Evans.</strong> I tend to describe myself as
            <i>wide-eyed, enthusiastic, and driven...</i>above all else I am passionate about technology. It
            inspires me and it is my catalyst to continue to learn, explore and push the boundaries
            of what we currently believe is possible.I began programming as a hobby in high school.
            Although I initially pursued my interest of film-making in college and earned a Bachelor of
            Science degree in Film, ultimately I realize that my true interest and career ambition was
            in Computer Science. I am currently enrolled at Western Governors University, studying
            Software Development with plans to graduate in 2019. In addition to a full-time job and
            course load, I still find time to freelance and assist small businesses with website
            development.

#---------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------- Projects Section --------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#

#---------------------------------------------------- Project 1 ----------------------------------------------------#
project-1Title: CPR-N-MORE.COM
project-1Blurb: <p>CPR-N-MORE was my first Website Development job and the place
                            I cut my teeth in web design and site development utilizing WordPress but
                            as both it and my knowledge grew it was refined...<br><u>More</u></p>
project-1MainContent: <img src="/portfolio/assets/img/projects/cprnmore/img-2.png" alt="">
                                        <p><strong>What is CPR-N-MORE.com?</strong></p>
                                        <p>CPR-N-MORE was my first Website Development job and the place
                                        I cut my teeth in web design and site development utilizing WordPress but
                                        as both it and my knowledge grew it was refined and morphed into the
                                        site it is today. Utilizing conventional HTML5 and custom CSS styling as
                                        well as the incorporation of APIs, I was able to create a product that
                                        incorporated both the owner's vision and requirements and in so doing,
                                        became the pivotal tool in the company's arsenal to reach CPR and First
                                        Aid clients throughout Missouri and Eastern Illinois, reportedly boosting
                                        sales and service by more than 70% through the creation of an online store
                                        for the purchase of AEDs and safety equipment and more importantly,
                                        created the platform for an interactive registration and payment hub for
                                        individual student registrations and large businesses alike.</p>
                                        <p><strong>Technologies Utilized:</strong></p>
                                        <p>HTML5, CSS3, JavaScript, WordPress and APIs
                                        (PayPal, Event Expresso)</p>
                                        <p><strong>The Story:</strong></p>
                                        <p>CPR-N-MORE is a St. Louis based CPR and AED sales and training
                                        company. I was one of the first independent contractors hired by the
                                        company and tasked with creating and maintain their online presence. The
                                        site was much more than a landing page for the company as it was the
                                        primary resource for potential students to register for upcoming course
                                        offerings. In the early days I managed the registration process utilizing a
                                        mixture of individual HTML pages for corresponding class and then
                                        linking them to a calendar, so customers could navigate to the class of
                                        their choosing with ease. Today it is a much different story, as we have
                                        integrated Event Espresso's API allowing us to maintain and customize
                                        multiple facets of the registration process and collect all pertinent data in a
                                        safe and secure way. Another major aspect of the website at its inception,
                                        was the e-commerce section of the site where the company sold AEDs
                                        and other various first aid and safety related merchandise. This aspect of
                                        the site was accomplished by integrating the PayPal API directly into the
                                        site and structuring the page to act as a virtual catalog for potential
                                        customers to browse the company’s online store. I learned an extensive
                                        amount during my time developing this site and look back on the
                                        experience as I move forward as a developer.</p>
                                        <p><strong>What I Learned:</strong></p>
                                        <p>I learned that you never stop learning  and each day that I worked on
                                        the website, I continued to learn something new. Additionally, I learned
                                        that value of strong problem-solving while addressing the many unknowns
                                        while creating the site.</p>
                                        <a href="#projects">top</a>


#---------------------------------------------------- Project 2 ----------------------------------------------------#
project-2Title: OnMax
project-2Blurb: <p>OnMax is a macro enabled workbook developed for Enterprise in
                            response to the overwhelming amount of data that the administrative
                            staff has to sift through to onboard each new hire class. The macro
                            automated the process and turned a drawn-out tedious task into just a few
                            clicks of the mouse..<br><u>More</u></p>
project-2MainContent: <img src="/portfolio/assets/img/projects/onmax/onmaxThumbnail.png" alt="">
                                        <p><strong>What is OnMax?</strong></p>
                                        <p>OnMax is a macro enabled workbook developed for Enterprise in
                                        response to the overwhelming amount of data that the administrative
                                        staff has to sift through to onboard each new hire class. The macro
                                        automated the process and turned a drawn-out tedious task into just a few
                                        clicks of the mouse..</p>
                                        <p><strong>Technologies Utilized:</strong></p>
                                        <p>VBA and Excel</p>
                                        <p><strong>The Story:</strong></p>
                                        <p>OnMax was macro enabled workbook developed for Enterprise
                                        Rent-A-Car, specifically for their administrative staff to help expedite the
                                        process of sifting through employee information and the creation of the
                                        relevant documentation to request anything form security codes to email
                                        access. The original process had the administrative staff sifting through a
                                        document with thirty+ different data points per employee and extracting
                                        only a hand full of them to create the required documents for each relevant
                                        department. This was a sub optimal and arduous task that could take
                                        multiple hours depending on the size of the income class of new hires.
                                        Therefore, I was tasked to find a solution, but found that the limiting
                                        factors of an all virtual environment without administrative access a
                                        hostile workplace for creativity. I was forced to think materialistically, but
                                        critically, the solution had to be small and piggyback off an already
                                        existing structure that the end user had access to on their virtual machine.
                                        After great deliberation I decided that the most practical solution would be
                                        to utilize a macro enabled work book in excel and write a custom VBA
                                        script to parse and array that data to be called into an independent excel
                                        sheet depending on the needs of the end user. VBA functions second
                                        nature within excel, and as it has similarity between both C and .NET it
                                        proved to be both versatile and comprehensive. As this application is still
                                        in use today, I believe the solution I provided did indeed meet expectations
                                        and a second revision with the ability for the end-user to input custom data
                                        on the fly is currently in the works.</p>
                                        <p><strong>What I Learned:</strong></p>
                                        <p>I learned that simplicity is not always a bad thing, sometimes the most
                                        elegant solutions are the simple ones. Additionally, limitations are not
                                        always a hurdle to overcome, but merely a byproduct of the environment at
                                        hand. Lastly, it’s better to fall back on what you know and deliver a
                                        solution that works, and then refine form there.</p>
                                        <a href="#projects">top</a>

#---------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------- Contact Section --------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#

social:
- {icon: 'github', link: 'https://github.com/MatthewEvans521'}
- {icon: 'twitter', link: 'http://twitter.com/MatthewEvans521'}
- {icon: 'facebook', link: 'https://www.facebook.com/matthewrevans'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/matthew-evans-9ba07bb6'}

#---------------------------------------------------------------------------------------------------------------------#
#------------------------------------------------- SEO Section ---------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: ''
  rel-publisher: ''

#---------------------------------------------------------------------------------------------------------------------#
#------------------------------------------ Google Analytics Section -------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------#

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#---------------------------------------------------------------------------------------------------------------------#
